### PR TITLE
Account for "empty" IisPipelineEvent

### LINKED ISSUE #1366: NullReferenceException opening IIS Stats
PerfView version: 2.0.65 (x86 and x64)

```text
Exception Occurred: System.NullReferenceException: Object reference not set to an instance of an object.
   at PerfView.PerfViewIisStats.WriteHtmlBody(TraceLog dataFile, TextWriter writer, String fileName, TextWriter log)
   at PerfView.PerfViewHtmlReport.GenerateReportFile(StatusBar worker, TraceLog trace)
   at PerfView.PerfViewHtmlReport.<>c__DisplayClass17_1.<Open>b__0()
   at PerfView.StatusBar.<>c__DisplayClass22_0.<StartWork>b__0()
````

### PR DESCRIPTION
**Pull request by paulomorgado**
Fixes #1366

### CODE REVIEW

File: src/PerfView/PerfViewData.cs [hunk 1]
```diff
@@ -2490,7 +2490,7 @@ private void AddGenericStopEventToRequest(Guid contextId, TraceEvent traceEvent,
         }
         private IisPipelineEvent GetSlowestEvent(IisRequest request)
         {
-            IisPipelineEvent slowestPipelineEvent = new IisPipelineEvent();
+            IisPipelineEvent slowestPipelineEvent = null;
```
Comment (brianrob) [inline src/PerfView/PerfViewData.cs:2493]: This looks like it could result in a null reference on line 2523.

Comment (paulomorgado) [reply src/PerfView/PerfViewData.cs:2493]: Fixed!

**Review by brianrob — APPROVED** [review]
